#!/usr/bin/bash
#This file was created on 4/4/2021


echo "-------------------------------"
echo "Network DNS"
grep "nameserver"  /etc/resolv.conf
echo "-------------------------------"

echo "IP -- Netmask -- Broadcast"
echo "-------------------------------"
ifconfig | grep 'inet [0-9\+.[0-9]\+.[0-9]\+.[0-9]\+'

echo "==============================="
netstat -lnt
